import type { BadgeProps } from '@/components/reui/badge'

/** 兼容现有字典的语义颜色，也允许直接指定 ReUI Badge 变体。 */
export const dictionaryBadgeVariants: ReadonlyMap<string, NonNullable<BadgeProps['variant']>> = new Map([
  ['primary', 'primary-light'],
  ['success', 'success-light'],
  ['warning', 'warning-light'],
  ['danger', 'destructive-light'],
  ['destructive', 'destructive-light'],
  ['info', 'info-light'],
  ['focus', 'focus-light'],
  ['invert', 'invert-light'],
  ['default', 'default'],
  ['outline', 'outline'],
  ['secondary', 'secondary'],
  ['primary-light', 'primary-light'],
  ['success-light', 'success-light'],
  ['warning-light', 'warning-light'],
  ['destructive-light', 'destructive-light'],
  ['info-light', 'info-light'],
  ['focus-light', 'focus-light'],
  ['invert-light', 'invert-light'],
  ['primary-outline', 'primary-outline'],
  ['success-outline', 'success-outline'],
  ['warning-outline', 'warning-outline'],
  ['destructive-outline', 'destructive-outline'],
  ['info-outline', 'info-outline'],
  ['focus-outline', 'focus-outline'],
  ['invert-outline', 'invert-outline'],
])
